project_id = "nvdkgfptnqardtxlqoym"

[functions.analyze-document]
verify_jwt = false

[functions.generate-form-app]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false